identifier = "custom.oakapp"
app_version = "1.0.0"

prepare_container = [
    { type = "RUN", command = "apt-get update" },
    { type = "RUN", command = "apt-get install -y python3 python3-pip wget git" },
]

prepare_build_container = []

build_steps = ["uv pip install -r /app/pyproject.toml --system"]

entrypoint = ["bash", "-c", "python3 /app/main.py"]

[base_image]
image_name = "astral/uv"
image_tag = "bookworm-slim"